/** Türkçe ürün adları — Supabase name_tr boş/Almanca kaldığında kullanılır. */
export const CATALOG_NAME_TR: Record<string, string> = {
  "noodle-fettuccine-classic": "Fettuccine klasik",
  "noodle-fettuccine-pesto": "Fettuccine pesto",
  "noodle-fettuccine-nero": "Fettuccine nero di seppia",
  "noodle-fettuccine-vegan-classic": "Fettuccine vegan klasik",
  "noodle-fettuccine-vegan-pesto": "Fettuccine vegan pesto",
  "pasta-klassisch": "Klasik makarna",
  "pasta-vegan": "Vegan makarna",
  "s-pesto-genovese": "Pesto Genovese sosu",
  "s-champignon-rahm": "Mantar krema sosu",
  "s-paprika-geroestet": "Közlenmiş biber sosu",
  "s-sweet-chili-cream": "Tatlı acı krema sosu",
  "s-zitronen-rahm": "Limonlu krema sosu",
  "s-spinat-parmesan": "Ispanak parmesan sosu",
  "s-vegane-parmesan-sahne": "Vegan parmesan krema sosu",
  "s-kokos-curry": "Hindistan cevizi köri sosu",
  "s-paprika-geroestet-v": "Közlenmiş biber sosu (vegan)",
  "s-spinat-knoblauch-v": "Ispanak sarımsak sosu",
  "s-sweet-chili-v": "Tatlı acı sos",
  "t-rindfleisch": "Dana eti",
  "t-haehnchen": "Tavuk",
  "t-pastrima": "Pastırma",
  "t-garnelen": "Karides",
  "t-mozzarella": "Mozzarella",
  "t-babyspinat": "Bebek ıspanak",
  "t-knoblauch-oel": "Sarımsak yağı",
  "t-walnuesse": "Ceviz",
  "t-feta": "Feta",
  "t-paprika-grill": "Izgara biber",
  "t-avocado": "Avokado",
  "t-aubergine-grill": "Izgara patlıcan",
  "t-zucchini": "Kabak",
  "t-champignons-extra": "Ekstra mantar",
  "t-rinder-bacon": "Dana bacon (helal)",
  "t-gorgonzola": "Gorgonzola",
  "t-extra-haehnchen": "Ekstra tavuk",
  "t-extra-garnelen": "Ekstra karides",
  "t-steakstreifen": "Biftek şeritleri",
  "t-thunfisch": "Ton balığı",
  "t-basilikum": "Taze fesleğen",
  "t-extra-knoblauch": "Ekstra sarımsak",
  "t-seitan": "Seitan",
  "t-tofu": "Tofu",
  "t-austernpilz": "İstiridye mantarı",
  "t-vegan-parmesan": "Ekstra vegan parmesan",
  "cs-bbq-chicken": "BBQ tavuklu makarna",
  "cs-curry-chicken": "Köri tavuklu makarna",
  "cs-beef-mushroom": "Kremalı dana mantar",
  "cs-burrata-cherry": "Burrata ve cherry domates",
  "cs-lemon-shrimp": "Limonlu karidesli makarna",
  "cs-spinach-parmesan": "Ispanak parmesan makarna",
  "cs-pastera-signature": "Pastera Signature",
  "vcs-creamy-parmesan": "Kremalı vegan parmesan",
  "vcs-curry-seitan": "Vegan köri seitan",
  "vcs-mediterranean": "Vegan Akdeniz",
  "vcs-paprika-deluxe": "Vegan biber deluxe",
  "vcs-spinach-supreme": "Vegan ıspanak supreme",
  "vcs-pastera-signature": "Pastera Signature Vegan",
  "s-tomatensauce": "Domates sosu",
  "s-bolognese": "Bolognese sosu",
  "s-sahnesauce": "Krema sosu",
  "s-currysauce": "Köri sosu",
  "s-pesto": "Pesto sosu",
  "s-arrabbiata": "Arrabbiata sosu",
  "s-vegane-tomatensauce": "Vegan domates sosu",
  "s-vegane-currysauce": "Vegan köri sosu",
  "s-vegane-sahnesauce": "Vegan krema sosu",
  "s-veganes-pesto": "Vegan pesto",
  "sp-haehnchen-mariniert": "Marine tavuk",
  "sp-curry-sahne-haehnchen": "Köri-krema tavuk",
  "sp-rind-mariniert": "Marine dana",
  "sp-schwarze-garnelen": "Kara karides",
  "sp-rinderfilet-demiglace": "Dana bonfile (demiglace)",
  "sp-seitan": "Seitan şeritleri",
  "sp-tofu": "Tofu",
  "t-brokkoli": "Brokoli",
  "t-rucola": "Roka",
  "t-blattspinat": "Ispanak",
  "t-cherrytomaten": "Cherry domates",
  "t-getrocknete-tomaten": "Kuru domates",
  "t-jalapenos": "Jalapeno",
  "t-champignons": "Mantar",
  "t-mais": "Mısır",
  "t-gruene-oliven": "Yeşil zeytin",
  "t-rote-zwiebeln": "Kırmızı soğan",
  "t-roestzwiebeln": "Karamelize soğan",
  "t-fruehlingszwiebeln": "Yeşil soğan",
  "t-mini-mozzarella": "Mini mozzarella",
  "t-pinienkerne": "Çam fıstığı",
  "t-extra-parmesan": "Ekstra parmesan",
  "suppe-aubergine-cremig": "Kremalı patlıcan çorbası",
  "vorspeise-auberginen-garnelen": "Izgara patlıcan ve karides",
  "vorspeise-pilzpfanne": "Mantar tavası (vegan)",
  "vorspeise-carpaccio": "Dana carpaccio",
  "vorspeise-rinderfiletstreifen": "Dana bonfile şeritleri",
  "vorspeise-city-chick-wings": "Tavuk kanatları",
  "d-wasser": "Sade su 0,5l",
  "d-sprudel": "Maden suyu",
  "d-cola": "Kola 0,33l",
  "d-limo": "Ev limonatası",
  "d-espresso": "Espresso",
  "d-wein": "Kırmızı şarap (kadeh)",
};

export function catalogNameTr(id: string, fallbackDe: string): string {
  return CATALOG_NAME_TR[id] ?? fallbackDe;
}
