/** Türkçe ürün adları */
export const CATALOG_NAME_TR: Record<string, string> = {
  "noodle-classic": "Klasik",
  "noodle-spinach": "Ispanaklı makarna",
  "noodle-vegan": "Vegan",
  "noodle-vegan-spinach": "Vegan ıspanaklı makarna",
  "noodle-black": "Klasik",
  "noodle-chocolate": "Çikolatalı makarna",
  "menu-kendin-yap": "Kendin yap",
  "menu-kendin-yap-vegan": "Vegan kendin yap",
  "s-tomatensauce": "Domates sosu",
  "s-domates-vegan": "Domates",
  "s-bolognese": "Bolognese",
  "s-curry": "Köri",
  "s-krema": "Krema",
  "s-pesto": "Pesto",
  "s-arrabbiata": "Arrabbiata",
  "s-trueffel": "Trüf sosu",
  "s-vegan-pesto": "Vegan pesto",
  "s-vegan-trueffel": "Vegan trüf sosu",
  "s-choc-dark": "Çikolata",
  "s-choc-white": "Beyaz çikolata",
  "t-julienne-rind": "Jülyen dana",
  "t-julienne-haehnchen": "Tavuk",
  "t-pastrami": "Pastrami",
  "t-jumbo-garnelen": "Jumbo karides",
  "t-tenders": "Tavuk tenders",
  "t-falafel": "Falafel",
  "t-tofu": "Tofu",
  "t-seitan": "Seitan",
  "t-cherry": "Çeri domates",
  "t-babyspinat": "Baby ıspanak",
  "t-mantar": "Mantar",
  "t-rucola": "Rukola",
  "t-ceviz": "Ceviz",
  "t-mais": "Mısır",
  "t-gorgonzola": "Gorgonzola",
  "t-rosmarin": "Rozmarin",
  "t-yesil-zeytin": "Yeşil zeytin",
  "t-kurutulmus-sogan": "Kızarmış soğan",
  "t-jalapeno": "Jalapeno",
  "t-sarimsak": "Sarımsak",
  "t-mozzarella": "Suda mozzarella",
  "t-taze-sogan": "Taze soğan",
  "t-kaju": "Kaju",
  "t-kirmizi-sogan": "Soğan",
  "t-pinienkerne": "Çam fıstığı",
  "t-extra-parmesan": "Ekstra parmesan",
  "t-kuru-domates": "Kurutulmuş domates",
  "t-badem": "Kavrulmuş badem",
  "t-choc-muz": "Muz",
  "t-choc-cilek": "Çilek",
  "t-choc-kiwi": "Kivi",
  "t-choc-birne": "Armut",
  "t-choc-passion": "Passion fruit",
  "std-bolognese-classico": "Bolognese Classico",
  "std-chicken-cremesosse": "Chicken Cremesoße",
  "std-tartufo-deluxe": "Tartufo Deluxe",
  "std-pesto-verde": "Pesto Verde",
  "std-manzo-cremoso": "Manzo Cremoso",
  "std-crunchy-chicken": "Crunchy Chicken",
  "std-funghi-cremoso": "Funghi Cremoso",
  "std-arrabbiata-piccante": "Arrabbiata Piccante",
  "d-tiramisu": "Tiramisu",
  "d-creme-brulee": "Crème brûlée",
  "dr-pastera-zitrone": "Pastera limonatası",
  "dr-fritz-kola": "fritz-kola Original",
  "dr-fritz-zero": "fritz-kola Super Zero",
  "dr-fritz-mischmasch": "fritz-kola Mischmasch",
  "dr-fritz-orange": "fritz-limo Orange",
};

export function catalogNameTr(id: string, fallbackDe: string): string {
  return CATALOG_NAME_TR[id] ?? fallbackDe;
}
