/** Türkçe ürün adları — Supabase name_tr boş/Almanca kaldığında kullanılır. */
export const CATALOG_NAME_TR: Record<string, string> = {
  "noodle-classic": "Classic",
  "noodle-vegan": "Vegan",
  "noodle-black": "Siyah",
  "noodle-chocolate": "Çikolatalı makarna",
  "s-domates-vegan": "Domates",
  "s-bolognese": "Bolognese",
  "s-curry": "Köri",
  "s-krema": "Krema",
  "s-pesto": "Pesto (vegan)",
  "s-arrabbiata": "Arrabbiata (vegan)",
  "s-choc-dark": "Çikolata",
  "s-choc-white": "Beyaz çikolata",
  "menu-kendin-yap": "Kendin yap",
  "t-julienne-rind": "Jülyen dana",
  "t-julienne-haehnchen": "Jülyen tavuk",
  "t-jumbo-garnelen": "Jumbo karides",
  "t-tenders": "Tavuk tenders",
  "t-falafel": "Falafel",
  "t-tofu": "Tofu",
  "t-seitan": "Seitan",
  "t-cherry": "Çeri domates",
  "t-babyspinat": "Baby ıspanak",
  "t-mantar": "Mantar",
  "t-rucola": "Rukola",
  "t-birne": "Armut",
  "t-brokkoli": "Brokoli",
  "t-ceviz": "Ceviz",
  "t-mais": "Mais",
  "t-gorgonzola": "Gorgonzola",
  "t-siyah-zeytin": "Siyah zeytin",
  "t-rosmarin": "Rozmarin",
  "t-yesil-zeytin": "Yeşil zeytin",
  "t-passion-fruit": "Passion fruit",
  "t-kurutulmus-sogan": "Kurutulmuş soğan",
  "t-jalapeno": "Jalapeno",
  "t-sarimsak": "Sarımsak",
  "t-mozzarella": "Suda mozzarella",
  "t-taze-sogan": "Taze soğan",
  "t-kaju": "Kaju",
  "t-choc-muz": "Muz",
  "t-choc-cilek": "Çilek",
  "t-choc-kiwi": "Kivi",
  "t-choc-birne": "Armut",
  "t-choc-passion": "Passion fruit",
  "t-choc-schoko": "Çikolata",
  "t-choc-weiss": "Beyaz çikolata",
  "std-pera-e-miel": "Pera E Miel",
  "std-kremali-tavuk": "Kremalı tavuk",
  "std-domates": "Domates soslu",
  "std-pesto-mozzarella": "Pesto (mozzarellalı)",
  "std-curry-tavuk": "Köri tavuklu",
  "std-bolognese": "Bolognese soslu",
  "std-manti": "Mantı",
  "d-tiramisu": "Tiramisu",
  "d-creme-brulee": "Crème brûlée",
  "pasta-klassisch": "Klasik makarna",
  "pasta-vegan": "Vegan makarna",
};

export function catalogNameTr(id: string, fallbackDe: string): string {
  return CATALOG_NAME_TR[id] ?? fallbackDe;
}
